version: '1.0'
services:
  mysql:
    image: mysql:latest
    container_name: json-bin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: json_bin
      MYSQL_USER: jsonbin
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-network

  spring-app:
    build: .
    container_name: jsonbin
    ports:
      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/json_bin
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql
    networks:
      - spring-network

volumes:
  mysql_data:

networks:
  spring-network: