spring:
  application:
    name: jsonbin
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
