### post
POST http://localhost:8080/api/v1/json/
Content-Type: application/json

{
  "payload": "{\"name\":\"hello\"}"
}

### post
POST http://localhost:8080/api/v1/json/
Content-Type: application/json

{
  "payload": "{\"name\":\"hyeonjae\",\"age\":35}"
}


### get
GET http://localhost:8080/api/v1/json/6887e971-8a66-4888-a99f-36df3c73891b?type=SIMPLE


### put
PUT http://localhost:8080/api/v1/json/2c7aef48-fdc8-4c4c-a3a9-453f0cf70cab
Content-Type: application/json

{
  "name": "hi"
}


### delete
DELETE http://localhost:8080/api/v1/json/2c7aef48-fdc8-4c4c-a3a9-453f0cf70cab


