### post
POST http://localhost:8080/api/v1/json/
Content-Type: application/json

{
  "payload": "{\"world\":\"hello\"}"
}


### post
POST http://localhost:8080/api/v1/json/
Content-Type: application/json

{
  "payload": "{\"name\":\"hyeonjae\",\"age\":35}"
}


### get
GET http://localhost:8080/api/v1/json/a52ace68-25a8-4b90-97e8-171687e81f53?type=DETAILs


### put
PUT http://localhost:8080/api/v1/json/a52ace68-25a8-4b90-97e8-171687e81f53
Content-Type: application/json

{
  "payload": "hi"
}


### delete
DELETE http://localhost:8080/api/v1/json/a52ace68-25a8-4b90-97e8-171687e81f53


### get
GET http://localhost:8080/kafka/test/hi
