### post
POST http://localhost:8080/api/v1/json/
Content-Type: application/json

{
  "payload": "{\"world\":\"hello\"}"
}


### post
POST http://localhost:8080/api/v1/json/
Content-Type: application/json

{
  "payload": "{\"name\":\"hyeonjae\",\"age\":35}"
}


### get
GET http://localhost:8080/api/v1/json/de712609-f8fc-4406-bfc2-d036a2aa12fe?type=DETAIL


### put
PUT http://localhost:8080/api/v1/json/2c7aef48-fdc8-4c4c-a3a9-453f0cf70cab
Content-Type: application/json

{
  "name": "hi"
}


### delete
DELETE http://localhost:8080/api/v1/json/dbdbde81-920b-4fed-9b9d-6ceada9b7772


### get
GET http://localhost:8080/kafka/test/hi
